const catalog={iranian:{'ایران خودرو':{'پژو ۲۰۷ اتومات':1120000000,'دنا پلاس توربو':1280000000,'تارا اتومات V4':1540000000,'رانا پلاس':810000000},'سایپا':{'شاهین پلاس اتومات':1390000000,'کوییک GX':610000000,'ساینا S':590000000},'کرمان موتور':{'کی‌ام‌سی J7':2450000000,'جک S5':2210000000}},foreign:{'تویوتا':{'کرولا ۲۰۲۴':5750000000,'کمری ۲۰۲۴':8200000000,'راوفور ۲۰۲۳':12600000000},'هیوندای':{'النترا ۲۰۲۳':5100000000,'توسان ۲۰۲۳':8250000000,'سانتافه ۲۰۱۷':7300000000},'کیا':{'سراتو ۲۰۱۸':4800000000,'اسپورتیج ۲۰۱۷':6700000000},'بی‌ام‌و':{'X1 مدل ۲۰۱۷':9500000000,'530i مدل ۲۰۱۸':15400000000},'چری':{'تیگو ۸ پرو مکس':4350000000,'آریزو ۶ پرو':2200000000}}};
let carType='iranian',saved=false;const $=id=>document.getElementById(id);const fa=n=>new Intl.NumberFormat('fa-IR').format(Math.round(n));
function fillBrands(){brand.innerHTML=Object.keys(catalog[carType]).map(x=>`<option>${x}</option>`).join('');fillModels()}
function fillModels(){model.innerHTML=Object.keys(catalog[carType][brand.value]).map(x=>`<option>${x}</option>`).join('')}
function fillYears(){const now=1405;year.innerHTML=Array.from({length:21},(_,i)=>`<option value="${now-i}">${fa(now-i)}</option>`).join('')}
document.querySelectorAll('.type-toggle button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.type-toggle button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');carType=btn.dataset.type;fillBrands()});brand.onchange=fillModels;fillYears();fillBrands();
priceForm.onsubmit=e=>{e.preventDefault();const base=catalog[carType][brand.value][model.value];const age=Math.max(0,1405-Number(year.value));const km=Number(mileage.value)||0;const bodyRates={clean:0,one:-.035,multi:-.085,full:-.16,accident:-.25};const ageFactor=Math.pow(.945,age);const expected=Math.max(8000,age*15000);const kmDelta=Math.max(-.13,Math.min(.07,(expected-km)/350000));const bodyDelta=bodyRates[body.value];const cityDelta=city.value==='تهران'?.012:city.value==='یزد'?-.008:0;const price=base*ageFactor*(1+kmDelta+bodyDelta+cityDelta);resultCar.textContent=`${brand.value}، ${model.value} مدل ${fa(year.value)}`;resultPrice.textContent=fa(price);resultRange.textContent=`${fa(price*.96)} تا ${fa(price*1.045)} تومان`;const bodyText={clean:'بدون افت بدنه',one:'۳.۵٪ افت بدنه',multi:'۸.۵٪ افت بدنه',full:'۱۶٪ افت بدنه',accident:'۲۵٪ افت بدنه'};factors.innerHTML=`<div class="factor ${age?'negative':'positive'}"><span>سال ساخت</span><b>${age?fa(Math.round((1-ageFactor)*100))+'٪ افت':'مدل روز'}</b></div><div class="factor ${kmDelta<0?'negative':'positive'}"><span>کارکرد</span><b>${kmDelta>=0?'+':''}${fa(Math.round(kmDelta*100))}٪</b></div><div class="factor ${body.value==='clean'?'positive':'negative'}"><span>وضعیت بدنه</span><b>${bodyText[body.value]}</b></div><div class="factor"><span>بازار شهر</span><b>${city.value}</b></div>`;result.classList.remove('hidden');result.scrollIntoView({behavior:'smooth',block:'center'})};
saveBtn.onclick=()=>{saved=!saved;saveBtn.textContent=saved?'♥ ذخیره شد':'♡ ذخیره';favCount.textContent=saved?'۱':'۰'};
const answers=[{keys:['۲۰۷','207'],text:'پژو ۲۰۷ بازار فروش خوب، قطعات فراوان و شتاب قابل‌قبولی دارد. مهم‌ترین معایبش فضای کم عقب، کیفیت مونتاژ متغیر، خشکی سواری و هزینه نگهداری گیربکس اتومات است. نمونه اتومات را حتماً با دیاگ و تست گیربکس بررسی کن.'},{keys:['دنا'],text:'دنا پلاس ظاهر و امکانات خوبی دارد و نسخه توربو کشش مناسبی ارائه می‌دهد. در مقابل، کابین عقب خیلی جادار نیست، کیفیت قطعات یکنواخت نیست و توربو به بنزین و نگهداری حساس‌تر است.'},{keys:['تارا'],text:'تارا اتاق جادار، صندوق بزرگ و ایمنی سازه‌ای بهتری نسبت به بسیاری از هم‌رده‌های داخلی دارد. طراحی کابین ساده، کیفیت بعضی متریال‌ها و عملکرد نه‌چندان سریع گیربکس از ضعف‌های آن است.'},{keys:['شاهین'],text:'شاهین فضای کابین خوب و طراحی قابل‌قبولی دارد. موتور توربو به سرویس منظم و بنزین باکیفیت حساس است و کیفیت مونتاژ بعضی نمونه‌ها نیاز به بررسی دقیق دارد.'},{keys:['کم خرج','کم‌خرج'],text:'برای انتخاب ماشین کم‌خرج باید بودجه، شهر، نوع استفاده و ترجیح دنده‌ای یا اتومات را بدانم. معمولاً مدل‌های تنفس طبیعی با قطعات فراوان، ریسک هزینه نگهداری کمتری دارند.'}];
function reply(q){const hit=answers.find(a=>a.keys.some(k=>q.includes(k)));return hit?hit.text:'برای جواب دقیق‌تر نام کامل خودرو، سال ساخت، نوع گیربکس و بودجه‌ات را هم بنویس. بعد مزایا، معایب، هزینه نگهداری و ارزش خریدش را بررسی می‌کنم.'}
chatForm.onsubmit=e=>{e.preventDefault();const q=question.value.trim();if(!q)return;messages.insertAdjacentHTML('beforeend',`<div class="message user">${q.replace(/[<>]/g,'')}</div>`);question.value='';setTimeout(()=>{messages.insertAdjacentHTML('beforeend',`<div class="message bot">${reply(q)}</div>`);messages.scrollTop=messages.scrollHeight},450);messages.scrollTop=messages.scrollHeight};document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{question.value=b.textContent;chatForm.requestSubmit()});
