const priceBoard=document.getElementById('priceBoard'),searchInput=document.getElementById('priceSearch'),photoCar=document.getElementById('photoCar'),photoInput=document.getElementById('carPhoto'),preview=document.getElementById('photoPreview'),drop=document.getElementById('dropZone');
let priceData=window.dailyPrices||[];
const marketCars=allCars.map(c=>({...c,price:catalog[c.type][c.brand][c.model]}));
let selectedMaker='ایران خودرو';
const showDailyPrice=value=>typeof value==='number'?`${fa(value)} تومان`:value;
function renderPrices(query=''){const q=query.trim();const rows=priceData.filter(c=>c.maker===selectedMaker&&(!q||c.name.includes(q)));priceBoard.classList.add('daily-list');priceBoard.innerHTML=rows.length?`<div class="daily-header"><span>خودرو</span><span>قیمت بازار</span><span>قیمت کارخانه</span></div>${rows.map(c=>`<article class="daily-row"><div class="daily-car"><b>${c.name}</b><small>${c.maker}</small></div><div class="daily-price ${typeof c.market==='number'?'':'unavailable'}"><b>${showDailyPrice(c.market)}</b><small>بازار آزاد</small></div><div class="daily-price ${typeof c.factory==='number'?'':'unavailable'}"><b>${showDailyPrice(c.factory)}</b><small>کارخانه / نمایندگی</small></div></article>`).join('')}`:'<p class="daily-empty">خودرویی با این نام پیدا نشد.</p>'}
async function startMarket(){renderPrices();const result=await window.loadMarketPrices();priceData=result.rows;const updated=document.getElementById('lastUpdate'),source=document.getElementById('marketSource');updated.textContent=result.updatedAt?new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(result.updatedAt)):'آخرین داده ذخیره‌شده';if(source)source.textContent=result.live?'متصل به منبع بازار':'در انتظار کلید API — نمایش آخرین داده ذخیره‌شده';renderPrices(searchInput.value)}
startMarket();document.getElementById('priceSearchBtn').onclick=()=>renderPrices(searchInput.value);searchInput.addEventListener('input',()=>renderPrices(searchInput.value));
document.querySelectorAll('#makerTabs button').forEach(button=>button.onclick=()=>{selectedMaker=button.dataset.maker;document.querySelectorAll('#makerTabs button').forEach(item=>item.classList.toggle('active',item===button));renderPrices(searchInput.value)});
photoCar.innerHTML+='<optgroup label="خودروهای ایرانی">'+marketCars.filter(c=>c.type==='iranian').map(c=>`<option value="${c.type}|${c.brand}|${c.model}">${c.brand} — ${c.model}</option>`).join('')+'</optgroup><optgroup label="خودروهای خارجی">'+marketCars.filter(c=>c.type==='foreign').map(c=>`<option value="${c.type}|${c.brand}|${c.model}">${c.brand} — ${c.model}</option>`).join('')+'</optgroup>';
photoInput.onchange=()=>{const file=photoInput.files[0];if(!file)return;if(file.type.startsWith('image/')){preview.src=URL.createObjectURL(file);drop.classList.add('has-preview')}else{drop.classList.remove('has-preview');drop.querySelector('strong').textContent='برگه کارشناسی PDF انتخاب شد'}};
document.getElementById('analyzePhoto').onclick=()=>{const box=document.getElementById('photoResult'),file=photoInput.files[0];if(!file){box.classList.remove('hidden');box.textContent='اول عکس خودرو یا برگه کارشناسی را انتخاب کن.';return}if(!photoCar.value){box.classList.remove('hidden');box.textContent='نام خودرو را هم انتخاب کن تا قیمت محاسبه شود.';return}const [type,b,m]=photoCar.value.split('|'),rates={clean:1,one:.965,multi:.915,full:.84,accident:.75},p=catalog[type][b][m]*rates[document.getElementById('photoCondition').value];box.classList.remove('hidden');box.innerHTML=`تخمین اولیه برای <b>${m}</b><br><strong>${fa(p)} تومان</strong><br><small>این تخمین فعلاً براساس مدل و وضعیت انتخابی شماست. خواندن خودکار عکس و برگه کارشناسی پس از اتصال هوش مصنوعی فعال می‌شود.</small>`};
