document.body.classList.add('intro-lock');
const intro=document.getElementById('carIntro'),finishIntro=()=>{intro.classList.add('finished');document.body.classList.remove('intro-lock')};
setTimeout(finishIntro,3500);intro.addEventListener('click',finishIntro);
const vMessages=document.getElementById('valuationMessages'),vInput=document.getElementById('valuationAnswer'),vSend=document.getElementById('valuationSend'),vOptions=document.getElementById('quickOptions'),restart=document.getElementById('restartValuation');
const allCars=[...Object.entries(catalog.iranian).flatMap(([b,ms])=>Object.keys(ms).map(m=>({type:'iranian',brand:b,model:m}))),...Object.entries(catalog.foreign).flatMap(([b,ms])=>Object.keys(ms).map(m=>({type:'foreign',brand:b,model:m})))];
let stage=0;const bodyMap={'بدون رنگ':'clean','یک لکه رنگ':'one','چند لکه رنگ':'multi','تمام رنگ':'full','تصادف سنگین':'accident'};
function bubble(text,who='bot',small=''){vMessages.insertAdjacentHTML('beforeend',`<div class="v-message ${who}">${who==='bot'?'<span class="mini-ai">AI</span>':''}<p>${text}${small?'<small>'+small+'</small>':''}</p></div>`);vMessages.scrollTop=vMessages.scrollHeight}
function options(items){vOptions.innerHTML=items.map(x=>`<button type="button">${x}</button>`).join('');vOptions.querySelectorAll('button').forEach(b=>b.onclick=()=>answer(b.textContent))}
function ask(text,placeholder,items=[]){setTimeout(()=>{bubble(text);vInput.placeholder=placeholder;vInput.value='';options(items);vInput.focus()},250)}
function digits(q){return q.replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d))}
function findCar(q){const clean=q.replace(/ي/g,'ی').replace(/ك/g,'ک').trim();return allCars.find(x=>clean.includes(x.model.replace(/\s*\d{4}/,''))||x.model.includes(clean)||clean.includes(x.brand)&&clean.split(' ').some(w=>w.length>2&&x.model.includes(w)))}
function answer(raw){const q=raw.trim();if(!q)return;bubble(q,'user');if(stage===0){const c=findCar(q);if(!c){ask('این مدل را پیدا نکردم؛ نام کامل‌ترش را بنویس.','مثلاً: تارا اتومات V4',allCars.slice(0,3).map(x=>x.model));return}carType=c.type;document.querySelectorAll('.type-toggle button').forEach(x=>x.classList.toggle('active',x.dataset.type===carType));fillBrands();brand.value=c.brand;fillModels();model.value=c.model;stage=1;ask('چه سالی ساخته شده؟','مثلاً ۱۴۰۲',['۱۴۰۴','۱۴۰۳','۱۴۰۲','۱۴۰۱'])}else if(stage===1){const n=Number(digits(q).replace(/[^0-9]/g,''));if(!n||n<1380||n>1405){ask('سال ساخت را بین ۱۳۸۰ تا ۱۴۰۵ وارد کن.','مثلاً ۱۴۰۲');return}year.value=String(n);stage=2;ask('چند کیلومتر کار کرده؟','مثلاً ۴۵۰۰۰',['صفر','۲۰ هزار','۵۰ هزار','۱۰۰ هزار'])}else if(stage===2){let n=q.includes('صفر')?0:Number(digits(q).replace(/[^0-9]/g,''));if(q.includes('هزار'))n*=1000;if(Number.isNaN(n)||n>900000){ask('کارکرد را به کیلومتر بنویس.','مثلاً ۴۵۰۰۰');return}mileage.value=n;stage=3;ask('وضعیت بدنه‌اش چطوره؟','وضعیت بدنه',Object.keys(bodyMap))}else if(stage===3){const key=Object.keys(bodyMap).find(k=>q.includes(k));if(!key){ask('یکی از وضعیت‌های بدنه را انتخاب کن.','وضعیت بدنه',Object.keys(bodyMap));return}body.value=bodyMap[key];stage=4;ask('ماشین در کدام شهر معامله می‌شود؟','نام شهر را بنویس',['تهران','یزد','تبریز','اصفهان'])}else if(stage===4){city.value=[...city.options].map(x=>x.value).find(x=>q.includes(x))||'سایر شهرها';stage=5;ask('وضعیت فنی چطوره؟','وضعیت فنی',['سالم و سرویس‌شده','نیاز به سرویس جزئی','ایراد فنی دارد'])}else if(stage===5){bubble('عالیه؛ اطلاعات کامل شد. الان قیمت تقریبی بازار را حساب می‌کنم.');options([]);vInput.parentElement.style.display='none';restart.classList.remove('hidden');setTimeout(()=>priceForm.requestSubmit(),700)}}
vSend.onclick=()=>answer(vInput.value);vInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();answer(vInput.value)}});vOptions.querySelectorAll('button').forEach(b=>b.onclick=()=>answer(b.textContent));restart.onclick=()=>location.reload();
